import { PropsWithChildren } from 'react';
import './globals.css';
import { Language } from '@/types/i18n';
import { i18nConfig } from '@/utils/i18n';
import { dir } from 'i18next';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18nConfig.locales.map((lang) => ({ lang }));
}

export type Params = {
  params: {
    lang: Language;
  };
};

function RootLayout({ children, params }: PropsWithChildren<Params>) {
  return (
    <html lang={params.lang} dir={dir(params.lang)}>
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
